# Queries

query GET_USER {
  user {
    id
    name
  }
}

query GET_USERS {
  users {
    id
    name
  }
}

# Queries with arguments

query GET_USER {
  user(id: "812") {
    id
    userName
    firstName
  }
}

# Query Variables

# variables
# {
#   "id": "812"
# }

query GET_USER($id: ID!) {
  user(id: $id) {
    id
    userName
    firstName
  }
}

# Aliases

query GET_POST {
  post860: post(id: "860") {
    id
    title
  }

  post(id: "342") {
    id
    title
  }
}

# Fragments

fragment post on Post {
  id
  title
  body
  createdAt
  indexRef
  unixTimestamp
}

query GET_POST {
  post860: post(id: "860") {
    id
    title
  }

  post(id: "342") {
    ...post
  }
}
